# Data Exploration

## Import

In [1]:
import pandas as pd

df = pd.read_csv('Sample_Superstore.csv', encoding='latin1')
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

## Cek Jumlah Baris dan Kolom

In [2]:
print("Jumlah Baris :", df.shape[0])
print("Jumlah Kolom :", df.shape[1])

Jumlah Baris : 9994
Jumlah Kolom : 21

## Cek nama kolom

In [3]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit'],
      dtype='object')

## Cek Tipe Data setiap kolom

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

## Cek nilai data

In [5]:
df.describe()

,Row ID,Postal Code,Sales,Quantity,Discount,Profit
count,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,4997.500000,55190.379428,229.858001,3.789574,0.156203,28.656896
std,2885.163629,32063.693350,623.245101,2.225110,0.206452,234.260108
min,1.000000,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2499.250000,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,4997.500000,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,7495.750000,90008.000000,209.940000,5.000000,0.200000,29.364000
max,9994.000000,99301.000000,22638.480000,14.000000,0.800000,8399.976000

## Cek Missing Value

In [6]:
df.isnull().sum()

Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

In [7]:
(df.isnull().sum()/len(df))*100

Row ID           0.0
Order ID         0.0
Order Date       0.0
Ship Date        0.0
Ship Mode        0.0
Customer ID      0.0
Customer Name    0.0
Segment          0.0
Country          0.0
City             0.0
State            0.0
Postal Code      0.0
Region           0.0
Product ID       0.0
Category         0.0
Sub-Category     0.0
Product Name     0.0
Sales            0.0
Quantity         0.0
Discount         0.0
Profit           0.0
dtype: float64

## Cek Data Duplikat

In [8]:
df.duplicated().sum()

0

## Nilai unik setiap kolom

In [9]:
for col in df.columns:
    print(col,":",df[col].nunique())

Row ID : 9994
Order ID : 5009
Order Date : 1237
Ship Date : 1334
Ship Mode : 4
Customer ID : 793
Customer Name : 793
Segment : 3
Country : 1
City : 531
State : 49
Postal Code : 631
Region : 4
Product ID : 1862
Category : 3
Sub-Category : 17
Product Name : 1850
Sales : 5825
Quantity : 14
Discount : 12
Profit : 7287

## Cek typo pada kolom yang bertipe data kategorikal

###  1. Ship Mode

In [10]:
df['Ship Mode'].value_counts()

Standard Class    5968
Second Class      1945
First Class       1538
Same Day           543
Name: Ship Mode, dtype: int64

### 2. Customer Name

In [11]:
df['Customer Name'].value_counts()

William Brown          37
John Lee               34
Matt Abelman           34
Paul Prost             34
Chloris Kastensmidt    32
                       ..
Lela Donovan            1
Anthony O'Donnell       1
Carl Jackson            1
Ricardo Emerson         1
Jocasta Rupert          1
Name: Customer Name, Length: 793, dtype: int64

### 3. Segment

In [12]:
df['Segment'].value_counts()

Consumer       5191
Corporate      3020
Home Office    1783
Name: Segment, dtype: int64

### 4. Country

In [13]:
df['Country'].value_counts()

United States    9994
Name: Country, dtype: int64

### 5. City

In [14]:
df['City'].value_counts()

New York City      915
Los Angeles        747
Philadelphia       537
San Francisco      510
Seattle            428
                  ...
Glenview             1
Missouri City        1
Rochester Hills      1
Palatine             1
Manhattan            1
Name: City, Length: 531, dtype: int64

### 6. State

In [15]:
df['State'].value_counts()

California              2001
New York                1128
Texas                    985
Pennsylvania             587
Washington               506
Illinois                 492
Ohio                     469
Florida                  383
Michigan                 255
North Carolina           249
Arizona                  224
Virginia                 224
Georgia                  184
Tennessee                183
Colorado                 182
Indiana                  149
Kentucky                 139
Massachusetts            135
New Jersey               130
Oregon                   124
Wisconsin                110
Maryland                 105
Delaware                  96
Minnesota                 89
Connecticut               82
Oklahoma                  66
Missouri                  66
Alabama                   61
Arkansas                  60
Rhode Island              56
Utah                      53
Mississippi               53
Louisiana                 42
South Carolina            42
Nevada                    39
Nebraska                  38
New Mexico                37
Iowa                      30
New Hampshire             27
Kansas                    24
Idaho                     21
Montana                   15
South Dakota              12
Vermont                   11
District of Columbia      10
Maine                      8
North Dakota               7
West Virginia              4
Wyoming                    1
Name: State, dtype: int64

### 7. Postal Code

In [16]:
df['Postal Code'].value_counts()

10035    263
10024    230
10009    229
94122    203
10011    193
        ...
27534      1
53186      1
32503      1
94509      1
63376      1
Name: Postal Code, Length: 631, dtype: int64

### 8. Region

In [17]:
df['Region'].value_counts()

West       3203
East       2848
Central    2323
South      1620
Name: Region, dtype: int64

### 9. Category

In [18]:
df['Category'].value_counts()

Office Supplies    6026
Furniture          2121
Technology         1847
Name: Category, dtype: int64

### 10. Sub-category

In [19]:
df['Sub-Category'].value_counts()

Binders        1523
Paper          1370
Furnishings     957
Phones          889
Storage         846
Art             796
Accessories     775
Chairs          617
Appliances      466
Labels          364
Tables          319
Envelopes       254
Bookcases       228
Fasteners       217
Supplies        190
Machines        115
Copiers          68
Name: Sub-Category, dtype: int64

## Cek outliers

### 1. Sales

Apakah ada transaksi dengan sales sangat besar?
Apakah sales tinggi selalu menghasilkan profit tinggi?

- Terdapat 1.167 transaksi dengan nilai penjualan di atas 498,93.
- Hal ini menunjukkan bahwa sehagian kecil transaksi memberikan kontribusi penjualan yang jauh lebih besar dibanding mayoritas transaksi lainnya.
- Artinya: tingginya penjualan tidak selalu menghasilkan keuntungan yang tinggi

In [20]:
Q1 = df['Sales'].quantile(0.25)
Q3 = df['Sales'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

outlier_sales = df[
    (df['Sales'] < lower_bound) |
    (df['Sales'] > upper_bound)
]

print("Jumlah Outlier Sales:", len(outlier_sales))
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

outlier_sales.head()

Jumlah Outlier Sales: 1167
Lower Bound: -271.71000000000004
Upper Bound: 498.93

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
11,12,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002033,Technology,Phones,Konftel 250 Conference phone - Charcoal black,911.4240,4,0.20,68.3568

In [21]:
# Produk apa yang menyebabkan Sales menjadi outlier?
# Lihat transaksi Sales terbesar

display(
    outlier_sales[
        ['Product Name',
         'Category',
         'Sales',
         'Profit',
         'Discount']
    ]
    .sort_values('Sales', ascending=False)
    .head(10)
)

,Product Name,Category,Sales,Profit,Discount
2697,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480,-1811.0784,0.5
6826,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,8399.9760,0.0
8153,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,6719.9808,0.0
2623,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,3919.9888,0.2
4190,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,5039.9856,0.0
9039,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740,4946.3700,0.0
4098,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950,4630.4755,0.0
4277,"3D Systems Cube Printer, 2nd Generation, Magenta",Technology,9099.930,2365.9818,0.0
8488,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950,2799.9840,0.0
6425,Canon imageCLASS 2200 Advanced Copier,Technology,8399.976,1119.9968,0.4

### 2. Profit

Transaksi dengan profit tertinggi
Transaksi dengan kerugian terbesar
Produk atau kategori apa yang menyebabkan profit negatif

In [22]:
Q1 = df['Profit'].quantile(0.25)
Q3 = df['Profit'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

outlier_profit = df[
    (df['Profit'] < lower_bound) |
    (df['Profit'] > upper_bound)
]

print("Jumlah Outlier Profit:", len(outlier_profit))
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

outlier_profit.head()

Jumlah Outlier Profit: 1881
Lower Bound: -39.724125
Upper Bound: 70.816875

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
7,8,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,TEC-PH-10002275,Technology,Phones,Mitel 5320 IP Phone VoIP phone,907.1520,6,0.20,90.7152
10,11,CA-2014-115812,6/9/2014,6/14/2014,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,90032,West,FUR-TA-10001539,Furniture,Tables,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092
13,14,CA-2016-161389,12/5/2016,12/10/2016,Standard Class,IM-15070,Irene Maddox,Consumer,United States,Seattle,...,98103,West,OFF-BI-10003656,Office Supplies,Binders,Fellowes PB200 Plastic Comb Binding Machine,407.9760,3,0.20,132.5922

In [23]:
# Produk apa yang paling menguntungkan dan paling merugikan?
# Cari profit tertinggi

display(
    outlier_profit[
        ['Product Name',
         'Category',
         'Sales',
         'Profit',
         'Discount']
    ]
    .sort_values('Profit', ascending=False)
    .head(10)
)

,Product Name,Category,Sales,Profit,Discount
6826,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,8399.9760,0.0
8153,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,6719.9808,0.0
4190,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,5039.9856,0.0
9039,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740,4946.3700,0.0
4098,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950,4630.4755,0.0
2623,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,3919.9888,0.2
509,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,6354.950,3177.4750,0.0
8488,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950,2799.9840,0.0
7666,Hewlett Packard LaserJet 3310 Copier,Technology,5399.910,2591.9568,0.0
6520,GBC DocuBind P400 Electric Binding System,Office Supplies,5443.960,2504.2216,0.0

In [24]:
# Cari kerugian terbesar

display(
    outlier_profit[
        ['Product Name',
         'Category',
         'Sales',
         'Profit',
         'Discount']
    ]
    .sort_values('Profit')
    .head(10)
)

,Product Name,Category,Sales,Profit,Discount
7772,Cubify CubeX 3D Printer Double Head Print,Technology,4499.985,-6599.9780,0.7
683,Cubify CubeX 3D Printer Triple Head Print,Technology,7999.980,-3839.9904,0.5
9774,GBC DocuBind P400 Electric Binding System,Office Supplies,2177.584,-3701.8928,0.8
3011,Lexmark MX611dhe Monochrome Laser Printer,Technology,2549.985,-3399.9800,0.7
4991,Ibico EPK-21 Electric Binding System,Office Supplies,1889.990,-2929.4845,0.8
3151,Cubify CubeX 3D Printer Double Head Print,Technology,1799.994,-2639.9912,0.7
5310,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,1525.188,-2287.7820,0.8
9639,Chromcraft Bull-Nose Wood Oval Conference Tabl...,Furniture,4297.644,-1862.3124,0.4
1199,GBC DocuBind P400 Electric Binding System,Office Supplies,1088.792,-1850.9464,0.8
2697,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480,-1811.0784,0.5

### 3. Discount

Apakah transaksi dengan diskon tinggi menghasilkan profit rendah?
Apakah ada pola kerugian pada transaksi yang diberi diskon besar?

In [25]:
Q1 = df['Discount'].quantile(0.25)
Q3 = df['Discount'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

outlier_discount = df[
    (df['Discount'] < lower_bound) |
    (df['Discount'] > upper_bound)
]

print("Jumlah Outlier Discount:", len(outlier_discount))
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

outlier_discount.head()

Jumlah Outlier Discount: 856
Lower Bound: -0.30000000000000004
Upper Bound: 0.5

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
14,15,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-AP-10002311,Office Supplies,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,5,0.8,-123.8580
15,16,US-2015-118983,11/22/2015,11/26/2015,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,76106,Central,OFF-BI-10000756,Office Supplies,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.544,3,0.8,-3.8160
28,29,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,OFF-BI-10000474,Office Supplies,Binders,Avery Recycled Flexi-View Covers for Binding S...,9.618,2,0.7,-7.0532
32,33,US-2015-150630,9/17/2015,9/21/2015,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,19140,East,OFF-BI-10001525,Office Supplies,Binders,"Acco Pressboard Covers with Storage Hooks, 14 ...",6.858,6,0.7,-5.7150
36,37,CA-2016-117590,12/8/2016,12/10/2016,First Class,GH-14485,Gene Hale,Corporate,United States,Richardson,...,75080,Central,FUR-FU-10003664,Furniture,Furnishings,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.920,5,0.6,-147.9630

In [26]:
# Apakah diskon tinggi menghasilkan profit atau justru rugi?
# Cari transaksi dengan diskon tertinggi

display(
    outlier_discount[
        ['Product Name',
         'Sales',
         'Profit',
         'Discount']
    ]
    .sort_values('Discount', ascending=False)
    .head(10)
)

,Product Name,Sales,Profit,Discount
14,Holmes Replacement Filter for HEPA Air Cleaner...,68.810,-123.8580,0.8
8074,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",13.748,-22.6842,0.8
2826,Avery Self-Adhesive Photo Pockets for Polaroid...,2.724,-4.3584,0.8
8021,Acco 6 Outlet Guardian Basic Surge Suppressor,4.992,-12.9792,0.8
8024,Acco Economy Flexible Poly Round Ring Binder,1.044,-1.8270,0.8
2768,APC 7 Outlet Network SurgeArrest Surge Protector,32.192,-80.4800,0.8
8033,"Avery Triangle Shaped Sheet Lifters, Black, 2/...",0.984,-1.4760,0.8
6797,Poly Designer Cover & Back,3.798,-6.0768,0.8
8073,GBC Instant Report Kit,6.470,-9.7050,0.8
8075,Fellowes Superior 10 Outlet Split Surge Protector,15.224,-38.8212,0.8

### 4. Quantity

In [27]:
Q1 = df['Quantity'].quantile(0.25)
Q3 = df['Quantity'].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - (1.5 * IQR)
upper_bound = Q3 + (1.5 * IQR)

outlier_quantity = df[
    (df['Quantity'] < lower_bound) |
    (df['Quantity'] > upper_bound)
]

print("Jumlah Outlier Quantity:", len(outlier_quantity))
print("Lower Bound:", lower_bound)
print("Upper Bound:", upper_bound)

outlier_quantity.head()

Jumlah Outlier Quantity: 170
Lower Bound: -2.5
Upper Bound: 9.5

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
113,114,CA-2014-115259,8/25/2014,8/27/2014,Second Class,RC-19960,Ryan Crowe,Consumer,United States,Columbus,...,43229,East,OFF-FA-10000621,Office Supplies,Fasteners,"OIC Colored Binder Clips, Assorted Sizes",40.096,14,0.2,14.5348
139,140,CA-2016-145583,10/13/2016,10/19/2016,Standard Class,LC-16885,Lena Creighton,Consumer,United States,Roseville,...,95661,West,FUR-FU-10001706,Furniture,Furnishings,Longer-Life Soft White Bulbs,43.120,14,0.0,20.6976
147,148,CA-2016-114489,12/5/2016,12/9/2016,Standard Class,JE-16165,Justin Ellison,Corporate,United States,Franklin,...,53132,Central,TEC-PH-10000215,Technology,Phones,Plantronics Cordless Phone Headset with In-lin...,384.450,11,0.0,103.8015
251,252,CA-2016-145625,9/11/2016,9/17/2016,Standard Class,KC-16540,Kelly Collister,Consumer,United States,San Diego,...,92037,West,TEC-AC-10003832,Technology,Accessories,Logitech P710e Mobile Speakerphone,3347.370,13,0.0,636.0003
329,330,US-2016-141544,8/30/2016,9/1/2016,First Class,PO-18850,Patrick O'Brill,Consumer,United States,Philadelphia,...,19143,East,OFF-LA-10001074,Office Supplies,Labels,Round Specialty Laser Printer Labels,100.240,10,0.2,33.8310

In [28]:
# Produk apa yang dibeli dalam jumlah sangat besar?

display(
    outlier_quantity[
        ['Product Name',
         'Sales',
         'Profit',
         'Quantity']
    ]
    .sort_values('Quantity', ascending=False)
    .head(10)
)

,Product Name,Sales,Profit,Quantity
113,"OIC Colored Binder Clips, Assorted Sizes",40.096,14.5348,14
1433,High-Back Leather Manager's Chair,1819.860,163.7874,14
8074,"Pressboard Covers with Storage Hooks, 9 1/2"" x...",13.748,-22.6842,14
7387,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",1336.440,387.5676,14
6628,PureGear Roll-On Screen Protector,279.860,134.3328,14
6499,Anker Ultra-Slim Mini Bluetooth 3.0 Wireless K...,279.860,64.3678,14
6488,Xerox 1883,295.456,96.0232,14
1363,Cardinal EasyOpen D-Ring Binders,38.388,-25.5920,14
1429,Avery 4027 File Folder Labels for Dot Matrix P...,427.420,196.6132,14
6131,"Global Push Button Manager's Chair, Indigo",767.214,161.9674,14

In [29]:
outlier_sales.sort_values(
    'Sales',
    ascending=False
).head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
2697,2698,CA-2014-145317,3/18/2014,3/23/2014,Standard Class,SM-20320,Sean Miller,Home Office,United States,Jacksonville,...,32216,South,TEC-MA-10002412,Technology,Machines,Cisco TelePresence System EX90 Videoconferenci...,22638.480,6,0.5,-1811.0784
6826,6827,CA-2016-118689,10/2/2016,10/9/2016,Standard Class,TC-20980,Tamara Chand,Corporate,United States,Lafayette,...,47905,Central,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,17499.950,5,0.0,8399.9760
8153,8154,CA-2017-140151,3/23/2017,3/25/2017,First Class,RB-19360,Raymond Buch,Consumer,United States,Seattle,...,98115,West,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,13999.960,4,0.0,6719.9808
2623,2624,CA-2017-127180,10/22/2017,10/24/2017,First Class,TA-21385,Tom Ashbrook,Home Office,United States,New York City,...,10024,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,11199.968,4,0.2,3919.9888
4190,4191,CA-2017-166709,11/17/2017,11/22/2017,Standard Class,HL-15040,Hunter Lopez,Consumer,United States,Newark,...,19711,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,10499.970,3,0.0,5039.9856
9039,9040,CA-2016-117121,12/17/2016,12/21/2016,Standard Class,AB-10105,Adrian Barton,Consumer,United States,Detroit,...,48205,Central,OFF-BI-10000545,Office Supplies,Binders,GBC Ibimaster 500 Manual ProClick Binding System,9892.740,13,0.0,4946.3700
4098,4099,CA-2014-116904,9/23/2014,9/28/2014,Standard Class,SC-20095,Sanjit Chand,Consumer,United States,Minneapolis,...,55407,Central,OFF-BI-10001120,Office Supplies,Binders,Ibico EPK-21 Electric Binding System,9449.950,5,0.0,4630.4755
4277,4278,US-2016-107440,4/16/2016,4/20/2016,Standard Class,BS-11365,Bill Shonely,Corporate,United States,Lakewood,...,8701,East,TEC-MA-10001047,Technology,Machines,"3D Systems Cube Printer, 2nd Generation, Magenta",9099.930,7,0.0,2365.9818
8488,8489,CA-2016-158841,2/2/2016,2/4/2016,Second Class,SE-20110,Sanjit Engle,Consumer,United States,Arlington,...,22204,South,TEC-MA-10001127,Technology,Machines,HP Designjet T520 Inkjet Large Format Printer ...,8749.950,5,0.0,2799.9840
6425,6426,CA-2016-143714,5/23/2016,5/27/2016,Standard Class,CC-12370,Christopher Conant,Consumer,United States,Philadelphia,...,19120,East,TEC-CO-10004722,Technology,Copiers,Canon imageCLASS 2200 Advanced Copier,8399.976,4,0.4,1119.9968

### Persentase outliers

In [30]:
outlier_summary = pd.DataFrame({
    'Kolom': ['Sales', 'Profit', 'Discount', 'Quantity'],
    'Jumlah Outlier': [
        len(outlier_sales),
        len(outlier_profit),
        len(outlier_discount),
        len(outlier_quantity)
    ]
})

outlier_summary['Persentase (%)'] = round(
    (outlier_summary['Jumlah Outlier'] / len(df)) * 100, 2
)

outlier_summary

      Kolom  Jumlah Outlier  Persentase (%)
0     Sales            1167           11.68
1    Profit            1881           18.82
2  Discount             856            8.57
3  Quantity             170            1.70

## Filtering

### 1. Cek profit negatif

In [41]:
df_filtered = df.copy()
df_filtered[df_filtered['Profit'] < 0]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Ratio,Discount Impact,Profit Status,Sales Category
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.400000,Medium Discount,Loss,High Sales
14,15,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Appliances,Holmes Replacement Filter for HEPA Air Cleaner...,68.8100,5,0.80,-123.8580,-1.800000,High Discount,Loss,Low Sales
15,16,US-2015-118983,2015-11-22,2015-11-26,Standard Class,HP-14815,Harold Pawlan,Home Office,United States,Fort Worth,...,Binders,Storex DuraTech Recycled Plastic Frosted Binders,2.5440,3,0.80,-3.8160,-1.500000,High Discount,Loss,Low Sales
23,24,US-2017-156909,2017-07-16,2017-07-18,Second Class,SF-20065,Sandra Flanagan,Consumer,United States,Philadelphia,...,Chairs,"Global Deluxe Stacking Chair, Gray",71.3720,2,0.30,-1.0196,-0.014286,Medium Discount,Loss,Low Sales
27,28,US-2015-150630,2015-09-17,2015-09-21,Standard Class,TB-21520,Tracy Blumstein,Consumer,United States,Philadelphia,...,Bookcases,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,7,0.50,-1665.0522,-0.540000,Medium Discount,Loss,High Sales
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9920,9921,CA-2016-149272,2016-03-15,2016-03-19,Standard Class,MY-18295,Muhammed Yedwab,Corporate,United States,Bryan,...,Binders,"GBC Pre-Punched Binding Paper, Plastic, White,...",22.3860,7,0.80,-35.8176,-1.600000,High Discount,Loss,Low Sales
9921,9922,CA-2014-111360,2014-11-24,2014-11-30,Standard Class,AT-10435,Alyssa Tate,Home Office,United States,Akron,...,Binders,Acco Expandable Hanging Binders,5.7420,3,0.70,-4.5936,-0.800000,High Discount,Loss,Low Sales
9931,9932,CA-2015-104948,2015-11-13,2015-11-17,Standard Class,KH-16510,Keith Herrera,Consumer,United States,San Bernardino,...,Bookcases,O'Sullivan Living Dimensions 3-Shelf Bookcases,683.3320,4,0.15,-40.1960,-0.058824,Low Discount,Loss,High Sales
9937,9938,CA-2016-164889,2016-06-03,2016-06-06,Second Class,CP-12340,Christine Phan,Corporate,United States,Los Angeles,...,Tables,Hon 61000 Series Interactive Training Tables,71.0880,2,0.20,-1.7772,-0.025000,Low Discount,Loss,Low Sales
9962,9963,CA-2015-168088,2015-03-19,2015-03-22,First Class,CM-12655,Corinna Mitchell,Home Office,United States,Houston,...,Bookcases,Bush Heritage Pine Collection 5-Shelf Bookcase...,383.4656,4,0.32,-67.6704,-0.176471,Medium Discount,Loss,Medium Sales

### 2. Cek sales negatif

In [42]:
df_filtered = df.copy()
df_filtered[df_filtered['Sales'] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Profit Ratio, Discount Impact, Profit Status, Sales Category]
Index: []

[0 rows x 25 columns]

### 3. Cek quantity negatif

In [43]:
df_filtered = df.copy()
df_filtered[df_filtered['Quantity'] < 0]

Empty DataFrame
Columns: [Row ID, Order ID, Order Date, Ship Date, Ship Mode, Customer ID, Customer Name, Segment, Country, City, State, Postal Code, Region, Product ID, Category, Sub-Category, Product Name, Sales, Quantity, Discount, Profit, Profit Ratio, Discount Impact, Profit Status, Sales Category]
Index: []

[0 rows x 25 columns]

## Grouping & Sorting

### 1. Discount vs Profit

In [44]:
df.groupby('Discount')[['Sales', 'Profit']].mean().sort_values(by='Profit', ascending=False)

               Sales      Profit
Discount
0.10      578.397351   96.055074
0.00      226.742074   66.900292
0.15      529.971567   27.288298
0.20      209.076940   24.702572
0.60       48.150000  -43.077212
0.30      454.742974  -45.679636
0.32      536.794770  -88.560656
0.70       97.177708  -95.874060
0.80       56.545853 -101.796797
0.40      565.134874 -111.927429
0.45      498.634000 -226.646464
0.50      892.705152 -310.703456

### 2. Profit by Category

Kategori mana yang paling berkontribusi terhadap profit?

In [45]:
profit_category = (
    df.groupby('Category')
      .agg({
          'Sales':'sum',
          'Profit':'sum'
      })
      .sort_values('Profit', ascending=False)
)

display(profit_category)

                       Sales       Profit
Category
Technology       836154.0330  145454.9481
Office Supplies  719047.0320  122490.8008
Furniture        741999.7953   18451.2728

### 3. Profit by Sub-Category

Sub-category mana yang paling menguntungkan dan paling merugikan?

In [46]:
profit_subcategory = (
    df.groupby('Sub-Category')
      .agg({
          'Sales':'sum',
          'Profit':'sum'
      })
      .sort_values('Profit')
)

display(profit_subcategory)

                    Sales      Profit
Sub-Category
Tables        206965.5320 -17725.4811
Bookcases     114879.9963  -3472.5560
Supplies       46673.5380  -1189.0995
Fasteners       3024.2800    949.5182
Machines      189238.6310   3384.7569
Labels         12486.3120   5546.2540
Art            27118.7920   6527.7870
Envelopes      16476.4020   6964.1767
Furnishings    91705.1640  13059.1436
Appliances    107532.1610  18138.0054
Storage       223843.6080  21278.8264
Chairs        328449.1030  26590.1663
Binders       203412.7330  30221.7633
Paper          78479.2060  34053.5693
Accessories   167380.3180  41936.6357
Phones        330007.0540  44515.7306
Copiers       149528.0300  55617.8249

### 4. Profit by Region

Region mana yang memberikan profit terbesar?

In [47]:
profit_region = (
    df.groupby('Region')
      .agg({
          'Sales':'sum',
          'Profit':'sum'
      })
      .sort_values('Profit', ascending=False)
)

display(profit_region)

               Sales       Profit
Region
West     725457.8245  108418.4489
East     678781.2400   91522.7800
South    391721.9050   46749.4303
Central  501239.8908   39706.3625

### 5. Discount Impact vs Profit

Kelompok diskon mana yang menghasilkan profit terbaik?

In [48]:
discount_profit = (
    df.groupby('Discount Impact')
      .agg({
          'Sales':'sum',
          'Profit':'mean'
      })
      .sort_values('Profit', ascending=False)
)

display(discount_profit)

                        Sales      Profit
Discount Impact
No Discount      1.087908e+06   66.900292
Low Discount     8.465222e+05   26.501571
High Discount    6.422874e+04  -89.438144
Medium Discount  2.985414e+05 -109.528873

### 6. Discount Impact vs Profit Ratio

Kelompok discount mana yang paling efisien menghasilkan keuntungan?

In [49]:
discount_ratio = (
    df.groupby('Discount Impact')
      .agg({
          'Profit Ratio':'mean'
      })
      .sort_values('Profit Ratio', ascending=False)
)

display(discount_ratio)

                 Profit Ratio
Discount Impact
No Discount          0.340160
Low Discount         0.174368
Medium Discount     -0.219727
High Discount       -1.138785

### 7. Profit vs Loss

Apakah transaksi rugi memiliki discount yang lebih tinggi dibanding transaksi untung?

In [50]:
profit_status = (
    df.groupby('Profit Status')
      .agg({
          'Sales':'sum',
          'Profit':'sum',
          'Discount':'mean'
      })
)

display(profit_status)

                      Sales       Profit  Discount
Profit Status
Loss           4.963940e+05 -156131.2857  0.469029
Profit         1.800807e+06  442528.3074  0.081044

### 8. Sales Category vs Profit

Apakah transaksi dengan sales tinggi selalu menghasilkan profit yang tinggi?

In [51]:
sales_category_profit = (
    df.groupby('Sales Category')
      .agg({
          'Sales':'mean',
          'Profit':'mean',
          'Profit Ratio':'mean'
      })
)

display(sales_category_profit)

                      Sales      Profit  Profit Ratio
Sales Category
High Sales      1269.349512  160.973931      0.098256
Low Sales         31.406884    5.345646      0.124650
Medium Sales     240.474853   25.350469      0.119790

# Analisa Korelasi

## 1. Sales vs Profit

In [52]:
df[['Sales','Profit']].corr()

           Sales    Profit
Sales   1.000000  0.479064
Profit  0.479064  1.000000

INTERPRETASI:
Ketika nilai penjualan (sales) meningkat, maka profit cenderung ikut meningkat.
Namun, hubungan tersebut tidak terlalu kuat, terdapat faktor lain selain sales yang turut memengaruhi profit perusahaan.

INSIGHT BISNIS:
Peningkatan penjualan cenderung memberikan dampak positif terhadap profit, namun sales yang tinggi belum tentu selalu menghasilkan profit yang tinggi.

## 2. Discount vs Profit

In [53]:
df[['Discount','Profit']].corr()

          Discount    Profit
Discount  1.000000 -0.219487
Profit   -0.219487  1.000000

INTERPRETASI:
Hasil tersebut mengindikasikan bahwa pemberian diskon yang lebih tinggi belum tentu menghasilkan keuntungan yang lebih besar. Sebaliknya, profit cenderung menurun ketika diskon meningkat, meskipun pengaruhnya tidak terlalu signifikan.

INSIGHT BISNIS:
pemberian diskon yang tinggi berpotensi menurunkan profit, meskipun pengaruhnya tidak terlalu besar terhadap keuntungan secara keseluruhan.

## 3. Discount vs Profit Ratio

In [54]:
df[['Discount','Profit Ratio']].corr()

              Discount  Profit Ratio
Discount      1.000000     -0.864452
Profit Ratio -0.864452      1.000000

INTERPRETASI:
Hasil analisis menunjukkan bahwa semakinbesar diskon yang diberikan, semakin rendah efisiensi keuntungan yang diperoleh perusahaan.
Temuan ini menunjukkan bahwa kebijakan diskon punya dampak yang cukup besar terhadap keuntungan perusahaan, sehingga perlu diatur dengan lebih hati-hati supaya tidak mengurangi profit berlebihan.

INSIGHT BISNIS:
Diskon merupakan faktor yang memengaruhi efisiensi keuntungan perusahaan. Pemberian diskon yang terlalu besar dapat mengurangi persentase keuntungan yang diperoleh dari setiap transaksi.

## 4. Quantity vs Profit

In [55]:
df[['Quantity','Profit']].corr()

          Quantity    Profit
Quantity  1.000000  0.066253
Profit    0.066253  1.000000

INTERPRETASI:
Hasil analisis menunjukkan ketika jumlah barang (quantity) yang terjual meningkat, profit juga cenderung meningkat, namun pengaruhnya sangat kecil sehingga hampir tidak terlihat.

INSIGHT BISNIS:
Menjual lebih banyak unit produk belum tentu menghasilkan profit yang lebih tinggi. Faktor lain seperti discount dan margin produk juga berperan dalam menentukan profitabilitas.

## 5. Quantity dan Sales

In [56]:
df[['Quantity','Sales']].corr()

          Quantity     Sales
Quantity  1.000000  0.200795
Sales     0.200795  1.000000

INTERPRETASI:
Hasil analisis menunjukkan ketika jumlah barang yang terjual meningkat, nilai sales juga cenderung ikut meningkat.

ISIGHT BISNIS:
Quantity berkontribusi terhadap peningkatan sales, namun tidak selalu berdampak langsung terhadap peningkatan profit.

## 6. Top 10 Profit Products

Produk apa yang paling menguntungkan?

In [57]:
top_profit_products = (
    df.groupby('Product Name')
      .agg({
          'Sales':'sum',
          'Profit':'sum',
          'Discount':'mean'
      })
      .sort_values('Profit', ascending=False)
      .head(10)
)

display(top_profit_products)

,Sales,Profit,Discount
Product Name,,,
Canon imageCLASS 2200 Advanced Copier,61599.824,25199.9280,0.120000
Fellowes PB500 Electric Punch Plastic Comb Binding Machine with Manual Bind,27453.384,7753.0390,0.240000
Hewlett Packard LaserJet 3310 Copier,18839.686,6983.8836,0.200000
Canon PC1060 Personal Laser Copier,11619.834,4570.9347,0.150000
"HP Designjet T520 Inkjet Large Format Printer - 24"" Color",18374.895,4094.9766,0.166667
Ativa V4110MDD Micro-Cut Shredder,7699.890,3772.9461,0.000000
"3D Systems Cube Printer, 2nd Generation, Magenta",14299.890,3717.9714,0.000000
Plantronics Savi W720 Multi-Device Wireless Headset System,9367.290,3696.2820,0.057143
Ibico EPK-21 Electric Binding System,15875.916,3345.2823,0.333333
Zebra ZM400 Thermal Label Printer,6965.700,3343.5360,0.000000

## 7. Top 10 Loss Products

Produk apa yang paling merugikan?

In [58]:
top_loss_products = (
    df.groupby('Product Name')
      .agg({
          'Sales':'sum',
          'Profit':'sum',
          'Discount':'mean'
      })
      .sort_values('Profit')
      .head(10)
)

display(top_loss_products)

,Sales,Profit,Discount
Product Name,,,
Cubify CubeX 3D Printer Double Head Print,11099.963,-8879.9704,0.533333
Lexmark MX611dhe Monochrome Laser Printer,16829.901,-4589.9730,0.400000
Cubify CubeX 3D Printer Triple Head Print,7999.980,-3839.9904,0.500000
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases,9917.640,-2876.1156,0.280000
Bush Advantage Collection Racetrack Conference Table,9544.725,-1934.3976,0.350000
GBC DocuBind P400 Electric Binding System,17965.068,-1878.1662,0.450000
Cisco TelePresence System EX90 Videoconferencing Unit,22638.480,-1811.0784,0.500000
Martin Yale Chadless Opener Electric Letter Opener,16656.200,-1299.1836,0.100000
Balt Solid Wood Round Tables,6518.754,-1201.0581,0.200000
BoxOffice By Design Rectangular and Half-Moon Meeting Room Tables,1706.250,-1148.4375,0.483333

In [59]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Country', 'City', 'State',
       'Postal Code', 'Region', 'Product ID', 'Category', 'Sub-Category',
       'Product Name', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Profit Ratio', 'Discount Impact', 'Profit Status', 'Sales Category'],
      dtype='object')

In [60]:
display(df.head())

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Profit Ratio,Discount Impact,Profit Status,Sales Category
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,0.1600,No Discount,Profit,Medium Sales
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,0.3000,No Discount,Profit,High Sales
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,0.4700,No Discount,Profit,Low Sales
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,-0.4000,Medium Discount,Loss,High Sales
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,0.1125,Low Discount,Profit,Low Sales

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 25 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Row ID           9994 non-null   int64
 1   Order ID         9994 non-null   object
 2   Order Date       9994 non-null   datetime64[ns]
 3   Ship Date        9994 non-null   datetime64[ns]
 4   Ship Mode        9994 non-null   object
 5   Customer ID      9994 non-null   object
 6   Customer Name    9994 non-null   object
 7   Segment          9994 non-null   object
 8   Country          9994 non-null   object
 9   City             9994 non-null   object
 10  State            9994 non-null   object
 11  Postal Code      9994 non-null   int64
 12  Region           9994 non-null   object
 13  Product ID       9994 non-null   object
 14  Category         9994 non-null   object
 15  Sub-Category     9994 non-null   object
 16  Product Name     9994 non-null   object
 17  Sales            9994 non-null   float64
 18  Quantity         9994 non-null   int64
 19  Discount         9994 non-null   float64
 20  Profit           9994 non-null   float64
 21  Profit Ratio     9994 non-null   float64
 22  Discount Impact  9994 non-null   object
 23  Profit Status    9994 non-null   object
 24  Sales Category   9994 non-null   object
dtypes: datetime64[ns](2), float64(4), int64(3), object(16)
memory usage: 1.9+ MB

In [62]:
df.to_excel('superstore_clean.xlsx', index=False)

In [63]:
import os

os.listdir()

['-1.14-windows.xml',
 '.bash_history',
 '.borland',
 '.cache',
 '.conda',
 '.condarc',
 '.continuum',
 '.dlv',
 '.gitconfig',
 '.go',
 '.idlerc',
 '.ipynb_checkpoints',
 '.ipython',
 '.jupyter',
 '.lesshst',
 '.m2',
 '.matplotlib',
 '.nbi',
 '.node_repl_history',
 '.packettracer',
 '.redhat',
 '.rmv',
 '.sonarlint',
 '.thumbnails',
 '.VirtualBox',
 '.vscode',
 '02_Data_Structures_with_Python.ipynb',
 '1777722262132-Assignment-sesi-23_Asma-Syahidah.ipynb',
 'AddTwoNumbers.java',
 'Advanced Exploratory Data Analysis Techniques in Python.ipynb',
 'Advanced Techniques in Python Data Visualization.ipynb',
 'anaconda3',
 'AppData',
 'Application Data',
 'ArrayMultidimensi.java',
 'asma.json',
 'asma.py',
 'Asma_50421227',
 'Assignment sesi 23_Asma Syahidah Faisal.ipynb',
 'battery-report.html',
 'Belajar Python1.ipynb',
 'belajar-javascript-dasar.html',
 'BelajarJava.class',
 'BIGMART SALES DATA-Copy2.ipynb',
 'BIGMART SALES DATA-VISUALISASI & EDA.ipynb',
 'BigMart Sales Data.csv',
 'BIGMART SALES DATA.ipynb',
 'Biner.java',
 'bubble sort_1.ipynb',
 'c',
 'Cisco Packet Tracer 8.2.0',
 'Cisco Packet Tracer 8.2.1',
 'class Laptop.java',
 'connectsql.ipynb',
 'Contacts',
 'Cookies',
 'CORATCORETPYTHON.ipynb',
 'coretcoret_statistik.ipynb',
 'Creative Cloud Files  asmasyafaisal11@gmail.com 73DB2DDC624FF1A30A495EB7@AdobeID',
 'DATA_CLEANING.ipynb',
 'DATA_COLLECTION.ipynb',
 'documentation',
 'Documents',
 'Downloads',
 'Drone.java',
 'employees.csv',
 'employees.html',
 'employees.json',
 'employees.txt',
 'Employe_Performance_dataset.csv',
 'Employe_Performance_dataset_clean.csv',
 'Employe_Performance_dataset_cleaned.csv',
 'Favorites',
 'Fundamental of Data Visualization.ipynb',
 'Game.class',
 'Game.java',
 'go',
 'hasil_penjualan.csv',
 'hello-world-file.html',
 'hello-world.html',
 'hello-world.js',
 'Hewan.java',
 'HYPOTHESIS.ipynb',
 'int n = 1;.java',
 'IntelGraphicsProfiles',
 'java',
 'KA YUMITA_MINI PROJECT 2 PYTHON 19 MEI 2026 (1).ipynb',
 'Kali.java',
 'Kelinci.java',
 'komentar.html',
 'Laptop.class',
 'Laptop.java',
 'LATIHANKAGGLETRAIN.ipynb',
 'LatihanPython1.ipynb',
 'LatihanPythonAdvanced9nomor.ipynb',
 'LatihanPythonIntermediateDataTypes.ipynb',
 'LatihanPythonTesting.ipynb',
 'LATIHAN_DATA DISTRIBUTION .ipynb',
 'LATIHAN_DATA_COLLECTION.ipynb',
 'LATIHAN_DESCRIPTIVE STATISTIC.ipynb',
 'Latihan_Employe_performance_dataset.ipynb',
 'Links',
 'Local Settings',
 'love1.ipynb',
 'Main.class',
 'main.go',
 'Main.java',
 'MediaGet2',
 'MenuWarungMakan.java',
 'Microsoft',
 'Minpro_Dashboard.ipynb',
 'Music',
 'My Documents',
 'NetHood',
 'NOVI PROJECT PYTHON 2(1).ipynb',
 'NOVI PROJECT PYTHON 2.ipynb',
 'NOVIII_PROJECT PYTHON 2(1)(1).ipynb',
 'NTUSER.DAT',
 'ntuser.dat.LOG1',
 'ntuser.dat.LOG2',
 'NTUSER.DAT{2ad838bb-efea-11ee-a54d-000d3a94eaa1}.TxR.0.regtrans-ms',
 'NTUSER.DAT{2ad838bb-efea-11ee-a54d-000d3a94eaa1}.TxR.1.regtrans-ms',
 'NTUSER.DAT{2ad838bb-efea-11ee-a54d-000d3a94eaa1}.TxR.2.regtrans-ms',
 'NTUSER.DAT{2ad838bb-efea-11ee-a54d-000d3a94eaa1}.TxR.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TM.blf',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000001.regtrans-ms',
 'NTUSER.DAT{2ad838bc-efea-11ee-a54d-000d3a94eaa1}.TMContainer00000000000000000002.regtrans-ms',
 'ntuser.ini',
 'OneDrive',
 'Oracle',
 'package.json',
 'penjualanrumah.java',
 'Pert2',
 'Player.java',
 'Postman',
 'Practical Session Data Visualization .ipynb',
 'PracticalLiveCoding15soal.ipynb',
 'PrintHood',
 'ProgramPolymorphism.java',
 'PYTHON2.ipynb',
 'Recent',
 'Sample_Superstore.csv',
 'Saved Games',
 'Searches',
 'SendTo',
 'Start Menu',
 'Sti_Trace.log',
 'superstore_clean.xlsx',
 'Templates',
 'testing1.ipynb',
 'TESTINGPYTHON2.ipynb',
 'train (1)-Copy1.csv',
 'train (1).csv',
 'tugas.java',
 'tugas.py',
 'tugas1.py',
 'tugas2.py',
 'tugasasma.py',
 'untitled',
 'untitled .ipynb',
 'Untitled Folder',
 'Untitled Folder 1',
 'Untitled Folder 2',
 'Untitled Folder 3',
 'Untitled Folder 4',
 'Untitled Folder 5',
 'Untitled Folder 6',
 'Untitled.ipynb',
 'untitled.txt',
 'Untitled1.ipynb',
 'untitled1.txt',
 'Untitled10.ipynb',
 'Untitled11.ipynb',
 'Untitled12.ipynb',
 'Untitled2.ipynb',
 'untitled2.txt',
 'Untitled3.ipynb',
 'Untitled4.ipynb',
 'Untitled5.ipynb',
 'Untitled6.ipynb',
 'Untitled7.ipynb',
 'Untitled8.ipynb',
 'Untitled9.ipynb',
 'VID-20220421-WA0021.mp4',
 'VID-20220421-WA0022.mp4',
 'VID-20220421-WA0024.mp4',
 'VID-20220421-WA0028.mp4',
 'VID-20220421-WA0032.mp4',
 'VID-20220421-WA0033.mp4',
 'Videos',
 'WarungMakanProgram.java',
 'WPS Cloud Files',
 'YUMITA_MINI PROJECT 2 PYTHON 19 MEI 2026.ipynb']

In [64]:
import os

os.getcwd()

'C:\\Users\\asmas'

In [65]:
df.to_excel('superstore_clean.xlsx', index=False)

print("File berhasil disimpan!")

File berhasil disimpan!

In [66]:
df.shape

(9994, 25)

In [67]:
import os

for file in os.listdir():
    if file.endswith('.xlsx'):
        print(file)

superstore_clean.xlsx